services:
  web:
    build:
      context: ..
      dockerfile: local_env/Dockerfile.simple
    container_name: shinkansen_web
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ../server:/var/www:cached
    networks:
      - shinkansen_network
    environment:
      - APP_ENV=development
      - APP_DEBUG=true
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: shinkansen_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: shinkansen
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: shinkansen
      MYSQL_PASSWORD: shinkansen
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - shinkansen_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: shinkansen_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - shinkansen_network

volumes:
  mysql_data:
    driver: local

networks:
  shinkansen_network:
    driver: bridge